feat: add disabled flag to color picker component
Wondermarin/react-color-palette pull request #72
Opened 2024-06-01 14:45 UTC by lucasvtiradentes

### Description of Change

Hi, I loved the package, simple and beautiful.

As I was using it to build my own ready-to-use UI components, I missed the disabled flag as prop.

It is useful for when you don't want the user to update the existing color. I can think in those examples:

a) when the current user does not have the permission to edit;
b) when you can not change the color once it was set;

Of course, another solution for those cases would be to only display the color in a badge for example, but in the end I wanted to contribute somehow. Plus, you can check it is common to have this disabled flag (e.g.: https://primereact.org/colorpicker/)
 
That's it guys. Quick overview and PR, if you found this a good idea please test it before merge. If don't think it is a good idea, no problem at all. ;)

2024-06-03 11:45 UTC, Wondermarin commented
LGTM.
I'll try to test the changes in the next 3 days. Thanks for your contribution!

2024-06-09 17:10 UTC, Wondermarin requested changes
We also need to update the documentation in `README.md` to include the new property.

2024-06-09 17:10 UTC, Wondermarin commented on src/components/interactive/interactive.component.tsx
> +      style={{ cursor: disabled ? "not-allowed" : "move" }}
Let's remove the `style` property and instead use `disabled={disabled}` and update the styles in CSS based on this property.

2024-06-09 17:10 UTC, Wondermarin commented on src/components/fields/fields.component.tsx
> +              disabled={disabled}
For inputs, it might also be a good idea to update the styles based on the `disabled` property.

2024-06-25 18:45 UTC, luizcieslak commented on src/components/interactive/interactive.component.tsx
> +  readonly disabled: boolean;
```suggestion
  readonly disabled?: boolean;
```

2024-06-25 18:45 UTC, luizcieslak commented on src/components/fields/fields.component.tsx
> +  readonly disabled: boolean;
```suggestion
  readonly disabled?: boolean;
```

2024-06-25 18:45 UTC, luizcieslak commented on src/components/alpha/alpha.component.tsx
> +  readonly disabled: boolean;
```suggestion
  readonly disabled?: boolean;
```

2024-06-25 18:45 UTC, luizcieslak commented on src/components/hue/hue.component.tsx
> +  readonly disabled: boolean;
```suggestion
  readonly disabled?: boolean;
```

`disabled` props should optional for all components as they might be used detached from `ColorPicker`.

2024-06-25 18:45 UTC, luizcieslak commented on src/components/saturation/saturation.component.tsx
> +  readonly disabled: boolean;
```suggestion
  readonly disabled?: boolean;
```

2024-09-10 02:59 UTC, Wondermarin commented
Since it seems work on this PR has been abandoned, I'm closing it. If anyone wants to implement it, please feel free to open a new PR.

2024-09-10 02:59 UTC, closed without merging